services:
  # Backend servisi
  - type: web
    name: fintech-ai-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000

  # Frontend servisi
  - type: web
    name: fintech-ai-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: fintech-ai-backend
          envVarKey: RENDER_EXTERNAL_URL 